### ISSUE TITLE
How to handle major jsdom updates

### ISSUE THREAD

**Issue by topa** [dmatteo/jsdomify#103]
Yesterday I ran into a problem, because of a minor jsdomify [update ](https://github.com/dmatteo/jsdomify/commit/38700c2dfc87e25b8d50a171f10fab65fc1b134d#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R10) (1.1.0 -> 1.1.1) which was in fact a major jsdom update (7.2.2 -> 8.04).

In my tests I set an [HTMLElement's style](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style) via the `.style` property which is in real browser in fact a read-only property - this is obviously my mistake. 
It seems like they fixed this behavior in jsdom 8.x.x. So my tests began "surprisingly" to fail.
However, this time it was undeniably my fault, it still shows another potential problem. Let my phrase this as a question: 

Should major jsdom updates lead to major jsdomify updates?

I think yes, because jsdomify is convinience wrapper around jsdom and major updates of jsdom could have breaking changes that would be hidden for users who do not have jsdom as direct dependency. 

What do you think?

**Comment by dmatteo** [comment]
Hey Paul,
you definitely have a point. I have been too hasty with doing a minor bump. Sorry about that.

I will release another minor version that uses jsdom7, and bump my major versions alongside jsdom
