### ISSUE TITLE
Change jsdom to peerDependencies?

### ISSUE THREAD

**Issue by anyong** [dmatteo/jsdomify#170]
So that we can simply use our own local copy of jsdom and don't need a separate version installed for this script?

Thanks.

**Comment by dmatteo** [comment]
I'm not entirely sure it's a good idea, especially considering that the eventual extra package that will be installed it's only gonna be there for development and not burden production.

Also NPM 3 it's pretty smart about dependencies management.

e.g. if you have `jsdom@8.2.0` installed already and then install jsdomify, it will just reuse that copy of jsdom without getting another one (like `NPM < 3` is doing)

Do you have a specific use case / problem you're trying to solve?
