### ISSUE TITLE
Version of jsdom is pretty old

### ISSUE THREAD

**Issue by vovacodes** [dmatteo/jsdomify#2]
Current version of `jsdom` is `5.6.0`, whereas in the project `jsdom@3.1.2` is being used. This probably should be updated

**Comment by vovacodes** [comment]
Ok, closing this, 'cause I figured out that starting from v 4.x `jsdom` dropped support of node in favor of io.js.

**Comment by dmatteo** [comment]
Yup, we have to rely on the node version for the time being, unfortunately.
