### ISSUE TITLE
Update jsdom version

### ISSUE THREAD

**Issue by Wilfred** [dmatteo/jsdomify#256]
jsdom has some bugs in 8.2 with `<select mulitple>` elements, which is fixed in 8.4.2: https://github.com/tmpvar/jsdom/blob/master/Changelog.md#841

Could you upgrade the version of jsdom? This should just be a matter of merging 
#255.

**Comment by dmatteo** [comment]
Hey, sorry about not replying earlier. 
I got overwhelmed by the amount of PRs Greenkeeper opened 😒 

I'll update JSDOM's version (and all the rest) very soon.

I will release a new minor for JSDOM 8.5 and a major for JSDOM 9.x, so you will be able to choose what you feel more appropriate for you.

**Comment by dmatteo** [comment]
I had to do some cleanup on the PR opened by Greenkeeper and I've relaxed the versioning for the devDependencies, so I should receive way less PRs in the future.

Anyway, done and released.
Thanks for your contribution!

**Comment by Wilfred** [comment]
Thanks!
