### ISSUE TITLE
XHR error when working with systemjs

### ISSUE THREAD

**Issue by unional** [dmatteo/jsdomify#338]
I'm working on a plugin system based on systemjs.
I am able to get it working on node and browser, so the config seems to be working.
However, it doesn't work when running test with `jsdom`.

Here is the test code:
```ts
import test from 'ava'

import jsdomify from 'jsdomify'

let createSystemJS
test.before(() => {
  delete require.cache[require.resolve('systemjs')]
  jsdomify.create(`<!DOCTYPE html><html><base href="file://${process.cwd()}/index.html"></html>`)
  createSystemJS = require('./createSystemJS').createSystemJS
})

test.after(() => {
  jsdomify.destroy()
})

test.only(async _t => {
  const sys = createSystemJS('npm-module')
  console.log(sys.getConfig())
  await sys.import('npm-module')
})
```

And the error message:
```sh
  Loading file:///Users/hwong/github/unional/some-issues/plugins/npm-module/package.json
  Unable to fetch package configuration file file:///Users/hwong/github/unional/some-issues/plugins/npm-module/package.json
  Resolving npm-module
  Loading npm-module
    XMLHttpRequest.error (node_modules/systemjs/dist/system.src.js:1456:14)
    invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:210:27)
    EventTargetImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:130:9)
    EventTargetImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:91:17)
    XMLHttpRequest.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:71:35)
    dispatchError (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:915:9)
    validCORSHeaders (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:930:7)
    receiveResponse (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:805:12)
    EventEmitter.client.on.res (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:626:38)
    process.nextTick (node_modules/jsdom/lib/jsdom/living/xhr-utils.js:96:35)
```

I have verified that when running with `jsdom`, it is calling XHR from there:
https://github.com/systemjs/systemjs/blob/master/src/fetch.js#L41-L92

This is more of an issue on `jsdom` rather than `jsdomify`, but since I'm using `jsdomify` I think it would be good to start from here so that anyone using `jsdomify` and encounter this issue can find it here.

You can see the error in this repo:
https://github.com/unional/some-issues/tree/systemjs-jsdomify

I have created a branch to demo this:

```sh
git clone https://github.com/unional/some-issues.git
cd some-issues
git checkout systemjs-jsdomify
npm install
npm test

# to run the browser code
npm run serve
# and open http://localhost:3000 in the browser and open dev console.
# you should see the logs
```

Node that there is a bug in `systemjs` that preventing the correct error message to be printed (it's fixed and pending for release).
You need to edit `node_modules/systemjs/dist/systemjs.src.js` line 97:
https://github.com/systemjs/systemjs/blob/master/dist/system.src.js#L97

```js
// change
function throwResolveError () {
// to
function throwResolveError (relUrl, parentUrl) {
```

**Comment by unional** [comment]
Reference: 
https://github.com/systemjs/systemjs/issues/1581
https://github.com/tmpvar/jsdom/issues/1733

**Comment by dmatteo** [comment]
Hi @unional, thanks for your issue. 
Can you recreate the same problem by just using `jsdom`? 

At one point I tried using `jsdomify` with `systemjs`, but gave up due to other priorities. I remember being a bit of an hassle due to the async nature of systemjs itself.

Fair warning: you will not find much support from the `jsdom` team as soon as you mention `jsdomify`. They're very much against what we're doing here.

**Comment by unional** [comment]
I've resolved this using `jsdom` directly. Needs to set `url`. Not sure can the same thing be done in `jsdomify`?
