### ISSUE TITLE
Use `browser` package.json field if we have `jsdomify` in a file

### ISSUE THREAD

**Issue by niftylettuce** [dmatteo/jsdomify#41]
Is it possible to somehow rewrite all `require` calls inside a scope of `jsdomify` to use `browser` field in NPM packages instead of using node runtimes?  Since it's jsdomify - it has `window` injected and therefore should be using bower/webpack/browser version of packages

**Comment by dmatteo** [comment]
It looks to me that you want to live in the browser, not in Node.js.
If that's the case you should probably use `jsdom` directly, as `jsdomify` is useful if you want to run your tests in Node.js
