### ISSUE TITLE
jsdomify.create should accept callback once dom created?

### ISSUE THREAD

**Issue by niftylettuce** [dmatteo/jsdomify#42]

**Comment by niftylettuce** [comment]
https://github.com/tmpvar/jsdom/blob/master/lib/jsdom.js#L106-L108

**Comment by niftylettuce** [comment]
we should use `.created` option that we pass

**Comment by niftylettuce** [comment]
you also need to add an `.eslintrc` file to this project with these contents:

``` json
{
  "ecmaFeatures": [
    "modules": true
  ]
}
```

**Comment by niftylettuce** [comment]
how can you accurately write a test for DOM if it has not been created yet?  this is not safe

**Comment by niftylettuce** [comment]
I had to articially do a `setTimeout` here because of this: https://github.com/niftylettuce/frisbee/blob/master/test/unit/browser.test.js#L21

**Comment by niftylettuce** [comment]
see discussion at https://github.com/tmpvar/jsdom/issues/1203#issuecomment-160722279

**Comment by dmatteo** [comment]
> you also need to add an .eslintrc file to this project with these contents:

I'm not using `eslint` at all at the moment, so I don't see how that's relevant

> how can you accurately write a test for DOM if it has not been created yet? this is not safe

I'm not entirely sure what you mean here, as I'm using `jsdom.jsdom` which is not async, except any script loading (see https://github.com/tmpvar/jsdom#for-the-hardcore-jsdomjsdom)

> see discussion at tmpvar/jsdom#1203 (comment)

I now saw this thread and replied. I didn't see better options to run the tests in Node.js, but maybe there are and I will be glad to explore them.
